// AUTO-GENERATED by scripts/i18n/gen-registry.js — DO NOT EDIT BY HAND.
// Regenerate with `npm run i18n:gen` (also runs in prebuild). Source: src/locales/*.ts + scripts/i18n/i18n.config.json.

export const LOCALES = [
  { code: "ar", label: "العربية", dir: "rtl" },
  { code: "en", label: "English", dir: "ltr" },
  { code: "fr", label: "Français", dir: "ltr" },
  { code: "ur", label: "اردو", dir: "rtl" },
  { code: "fil", label: "Filipino", dir: "ltr" },
  { code: "ru", label: "Русский", dir: "ltr" },
  { code: "de", label: "Deutsch", dir: "ltr" },
  { code: "hi", label: "हिन्दी", dir: "ltr" },
  { code: "id", label: "Bahasa Indonesia", dir: "ltr" },
  { code: "zh", label: "中文", dir: "ltr" },
] as const;

export type Locale = (typeof LOCALES)[number]["code"];

export const DEFAULT_LOCALE: Locale = "ar";
