// AUTO-GENERATED by scripts/i18n/gen-registry.js — DO NOT EDIT BY HAND.
// Regenerate with `npm run i18n:gen` (also runs in prebuild). Source: src/locales/*.ts + scripts/i18n/i18n.config.json.

import { ar } from "./ar";
import { en } from "./en";
import { fr } from "./fr";
import { ur } from "./ur";
import { fil } from "./fil";
import { ru } from "./ru";
import { de } from "./de";
import { hi } from "./hi";
import { id } from "./id";
import { zh } from "./zh";
import type { Locale } from "@/lib/locales";

export const DICTS: Record<Locale, Record<string, string>> = {
  ar,
  en,
  fr,
  ur,
  fil,
  ru,
  de,
  hi,
  id,
  zh,
};
